kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: test
  image: ubuntu:latest
  commands:
  - apt-get update
  - apt-get install -y coreutils make gnutls-bin emacs-nox nodejs npm
  - make dependencies
  - make test
  - make lint
